// models/Claim.js

import mongoose from "mongoose";

const ClaimSchema = new mongoose.Schema(
    {
        // Transaction for which claim is generated
        transaction: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Transaction",
            required: true,
            index: true
        },

        // Card used
        cardType: {
            type: String,
            required: true,
            default: "amex_platinum"
        },

        // purchaseProtection, returnProtection, etc.
        benefitType: {
            type: String,
            required: true,
            index: true
        },

        // Current status
        status: {
            type: String,
            enum: [
                "pending",
                "ready_to_submit",
                "submitted",
                "approved",
                "rejected"
            ],
            default: "pending"
        },

        // Amount eligible under benefit
        eligibleAmount: {
            type: Number,
            required: true
        },

        // Amount actually claimed
        claimedAmount: {
            type: Number,
            default: 0
        },

        // Documents required
        requiredDocuments: {
            type: [String],
            default: []
        },

        // Documents uploaded by user
        uploadedDocuments: {
            type: [String],
            default: []
        },

        // Why this claim was generated
        reason: {
            type: String,
            default: ""
        },

        // Extra metadata from rules engine
        metadata: {
            type: mongoose.Schema.Types.Mixed,
            default: {}
        },

        // Claim deadlines
        deadline: {
            type: Date
        },

        // Auto generated?
        autoGenerated: {
            type: Boolean,
            default: true
        },

        // Manual notes
        notes: {
            type: String,
            default: ""
        }

    },
    {
        timestamps: true
    }
);

/**
 * Check whether all required
 * documents are uploaded.
 */
ClaimSchema.methods.isReadyToSubmit = function () {

    return this.requiredDocuments.every(doc =>
        this.uploadedDocuments.includes(doc)
    );

};

/**
 * Update status automatically.
 */
ClaimSchema.methods.refreshStatus = function () {

    if (this.isReadyToSubmit()) {

        this.status = "ready_to_submit";

    }
    else {

        this.status = "pending";

    }

};

/**
 * Upload a document.
 */
ClaimSchema.methods.addDocument = function (documentName) {

    if (!this.uploadedDocuments.includes(documentName)) {

        this.uploadedDocuments.push(documentName);

    }

    this.refreshStatus();

};

/**
 * Mark claim submitted.
 */
ClaimSchema.methods.submit = function () {

    if (!this.isReadyToSubmit()) {

        throw new Error(
            "Required documents are missing."
        );

    }

    this.status = "submitted";

};

export default mongoose.model(
    "Claim",
    ClaimSchema
);